# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DysCritique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dysfonctionnement', models.ImageField(upload_to='static/img/critique')),
                ('ImageVerso', models.ImageField(upload_to='static/img/critique')),
                ('Nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DysStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dysfonctionnement', models.ImageField(upload_to='static/img/standard')),
                ('ImageVerso', models.ImageField(upload_to='static/img/standard')),
                ('Nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rattrapage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=128)),
                ('Dysfonctionnement', models.ImageField(upload_to='static/img/rattrapage')),
                ('ImageVerso', models.ImageField(upload_to='static/img/rattrapage')),
                ('Nom', models.CharField(max_length=20)),
            ],
        ),
    ]
