# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdP', '0002_dyscritique_dysstandard_rattrapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyscritique',
            name='Dysfonctionnement',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dyscritique',
            name='ImageVerso',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dysstandard',
            name='Dysfonctionnement',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dysstandard',
            name='ImageVerso',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rattrapage',
            name='Dysfonctionnement',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rattrapage',
            name='ImageVerso',
            field=models.CharField(max_length=128),
        ),
    ]
