# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PdP', '0003_auto_20160421_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dyscritique',
            old_name='Dysfonctionnement',
            new_name='dysfonctionnement',
        ),
        migrations.RenameField(
            model_name='dyscritique',
            old_name='ImageVerso',
            new_name='imageVerso',
        ),
        migrations.RenameField(
            model_name='dyscritique',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dysstandard',
            old_name='Dysfonctionnement',
            new_name='dysfonctionnement',
        ),
        migrations.RenameField(
            model_name='dysstandard',
            old_name='ImageVerso',
            new_name='imageVerso',
        ),
        migrations.RenameField(
            model_name='dysstandard',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='rattrapage',
            old_name='Categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='rattrapage',
            old_name='Dysfonctionnement',
            new_name='dysfonctionnement',
        ),
        migrations.RenameField(
            model_name='rattrapage',
            old_name='ImageVerso',
            new_name='imageVerso',
        ),
        migrations.RenameField(
            model_name='rattrapage',
            old_name='Nom',
            new_name='nom',
        ),
    ]
