# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdP', '0005_auto_20160421_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_colors', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='blueeq',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='greeneq',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='redeq',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='yelloweq',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
    ]
